
PROJECT:
    NAME: MTBS
    ENTITY: wildfire

# wandb setting
dryrun: False
wandb_project: mtbs
run_name: mtbs-test
log_artifact_every: #int or list of int, if -1, log the last epoch
log_weight_every: 

seed: 0
use_gpu: True
debug: False # if debug, don't save checkpoints
CUDA_VISIBLE_DEVICES: # for local test runs
early_stop: False
log_cfmatrix_every: 1
save_model_top_k: # int
save_model_every: # int
save_model_last: # boolean

DATASET:
    name: MTBS
    data_dir: 'data/train'
    shuffle: False
    use_aug: False
    flip_p: 0.2
    aug_times: 1
      # data loader
    n_val: 0.1
    n_test: 0.2
    batch_size: 16
    num_workers: 4

TRAIN:
    n_epoch: 500 # 1024

    # optimizer
    lr: 0.0001
    use_scheduler: True
    warmup: 0
    # regularization
    wdecay: 0.002
    loss_lambda: 1

    # scheduler
    scheduler: steplr
    step_size: 30
    steplr_gamma: 0.4

    ema_used: False
    ema_decay: 0.999


RAND: # Rrproduce Results
    SEED: 42
    DETERMIN: False

DATA:
    NAME: s1s2
    data_dir: /home/p/u/puzhao/wildfire-s1s2-dataset-us-tiles/train
    # DIR: /cephyr/NOBACKUP/groups/snic2021-7-104/wildfire-s1s2-dataset-ak-tiles
    # DIR: /cephyr/NOBACKUP/groups/snic2021-7-104/wildfire-s1s2-dataset-ca-tiles

    satellites: ['S2']
    prepost: ['pre', 'post']
    stacking: True # stack bi-temporal data

    input_bands:
        ALOS: ['ND', 'VH', 'VV']
        S1: ['ND', 'VH', 'VV']
        S2: ['B4', 'B8', 'B12'] #['B4', 'B8', 'B12']
        # S2: ['B3', 'B8', 'B12'] #['B4', 'B8', 'B12']
    classes: ['unburn', 'low', 'moderate', 'high']

    # REF_MASK: poly
    train_mask: mtbs
    test_mask: mtbs
    val_ratio: 0.1
    test_ratio: 0.2
    use_aug: False
    num_workers: 4
    batch_size: 16

MODEL:
    DEBUG: True

    ARCH: UNet # UNet_dualHeads #UNet_resnet18 #FuseUNet, UNet
    USE_DECONV: False
    TOPO: [16, 32, 64, 128]
    LOSS_TYPE: CrossEntropyLoss # DiceLoss
    ACTIVATION: softmax2d  

    NUM_CLASS: 4
    CLASS_NAMES: ${DATA.classes} #'greener', 'cloud'
    CLASS_WEIGHTS: [0.25, 0.25, 0.25, 0.25]

    # NUM_CLASSES: 2
    # CLASS_NAMES: ['unburn','low'] #'greener', 'cloud'
    # CLASS_WEIGHTS: [0.5,0.5]

    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_DEPTH: 4
    ENCODER_WEIGHTS: imagenet

    MAX_EPOCH: 10
    BATCH_SIZE: ${DATA.batch_size}

    LEARNING_RATE: 1e-4
    WEIGHT_DECAY: 1e-2
    LR_SCHEDULER:  poly # ['cosine', 'poly']
    POLY_SCHEDULER:
        END_LR: 1e-5
        POWER: 0.9
    COSINE_SCHEDULER:
        WARMUP: 10
    
    MAX_SCORE: 0.1 # If IoU > max_score, save model
    SAVE_INTERVAL: 5 # save model frequency
    STEP_WISE_LOG: False # log metrics every step/update
    VERBOSE: True

EVAL:
    PATCHSIZE: 512
    MODE: prg # test # prg
    DIR: /home/p/u/puzhao/wildfire-s1s2-dataset-ak-tiles
    # PRG_DIR: /home/p/u/puzhao/wildfire-progression-dataset/CA_2021_Kamloops
    PRG_DIR: /home/p/u/puzhao/wildfire-progression-dataset/US_2021_Dixie

EXP:
    NOTE: debug
    FOLDER: MTBS_Burn_Severity
    NAME: ${DATA.train_mask}_${MODEL.ARCH}_${DATA.satellites}_${EXP.NOTE}
    OUTPUT: /home/p/u/puzhao/run_results/${EXP.FOLDER}/run_${EXP.NAME}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${EXP.OUTPUT}